import { access, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import path from "node:path";
import type { DesktopSettings, LocalProxySettings } from "../shared/types.js";
import type { DesktopPaths } from "./paths.js";
import { resolveConfiguredDataDirectory } from "./paths.js";

export interface AgentConfigResult {
  configPath: string;
  dataDirectory: string;
  adapterGuid: string;
}

export async function ensureAgentConfig(
  paths: DesktopPaths,
  settings: DesktopSettings
): Promise<AgentConfigResult> {
  await mkdir(paths.configDirectory, { recursive: true });
  let existing: string | null = null;
  try {
    await access(paths.configPath);
    existing = await readFile(paths.configPath, "utf8");
  } catch {
    // The first enrollment creates the production convention-based config.
  }

  if (existing === null) {
    const adapterGuid = randomUUID();
    const content = renderGeneratedAgentConfig(paths.dataDirectory, settings, adapterGuid, settings.proxy);
    await atomicWrite(paths.configPath, content);
    return { configPath: paths.configPath, dataDirectory: paths.dataDirectory, adapterGuid };
  }

  const adapterGuid = readAdapterGuid(existing) ?? randomUUID();
  const updated = updateConnectionFields(existing, settings);
  await atomicWrite(paths.configPath, updated);
  return {
    configPath: paths.configPath,
    dataDirectory: resolveConfiguredDataDirectory(paths.configPath, paths.dataDirectory),
    adapterGuid
  };
}

export function renderGeneratedAgentConfig(
  dataDirectory: string,
  settings: DesktopSettings,
  adapterGuid: string,
  proxy: LocalProxySettings = settings.proxy
): string {
  const dataPath = yamlString(dataDirectory);
  const wintunPath = "~/.tailcat-mesh/virtual-lan/windows/wintun.dll";
  const tun2SocksPath = "~/.tailcat-mesh/virtual-lan/windows/tun2socks.exe";
  const proxyLines = renderProxySection(proxy);
  return [
    "# Generated by Tailcat Mesh Desktop. Runtime settings remain Agent-owned.",
    "server:",
    `  url: ${yamlString(settings.serverUrl)}`,
    "",
    "device:",
    `  name: ${yamlString(settings.deviceName)}`,
    "",
    ...proxyLines,
    "tailcat:",
    "  version: 0.3.0",
    "  autoDownload: true",
    "  supportedVersion: 0.3.x",
    "  serverKey: tailcat-mesh-server",
    "  clientKey: tailcat-mesh-client",
    "  fullAddress: true",
    "",
    "agent:",
    `  dataDir: ${dataPath}`,
    "  heartbeatSeconds: 15",
    "  peerPingSeconds: 30",
    "",
    "# Capability is enabled; TUN/tun2socks processes remain demand-driven by Server desired state.",
    "virtualLan:",
    "  enabled: true",
    "  interfaceName: TailcatMesh",
    `  adapterGuid: ${adapterGuid}`,
    `  wintunDll: ${wintunPath}`,
    `  tun2socksBinary: ${tun2SocksPath}`,
    "  workingDirectory: ~/.tailcat-mesh/virtual-lan/windows",
    "  tun2socksArguments:",
    "    - --device",
    `    - tun://\${tun}?guid={${adapterGuid}}`,
    "    - --proxy",
    "    - \${proxy}",
    "    - --loglevel",
    "    - info",
    "  commandTimeoutSeconds: 15",
    "  startupTimeoutSeconds: 20",
    "",
    "forward:",
    "  defaultBindHost: 127.0.0.1",
    "",
    "logging:",
    "  level: INFO",
    ""
  ].join("\n");
}

export function readAdapterGuid(content: string): string | null {
  const match = content.match(/^\s+adapterGuid\s*:\s*([0-9a-fA-F-]{36})\s*(?:#.*)?$/m);
  return match?.[1] ?? null;
}

function updateConnectionFields(content: string, settings: DesktopSettings): string {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  setYamlField(lines, "server", "url", yamlString(settings.serverUrl));
  setYamlField(lines, "device", "name", yamlString(settings.deviceName));
  updateProxySection(lines, settings.proxy);
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

function updateProxySection(lines: string[], proxy: LocalProxySettings | undefined): void {
  const sectionIndex = lines.findIndex((line) => /^proxy:\s*$/.test(line));
  if (!isUsableProxy(proxy)) {
    if (sectionIndex >= 0) {
      removeYamlSection(lines, sectionIndex);
    }
    return;
  }
  if (sectionIndex < 0) {
    while (lines.length > 0 && lines[lines.length - 1] === "") {
      lines.pop();
    }
    if (lines.length > 0) {
      lines.push("");
    }
    lines.push(...renderProxySection(proxy));
    return;
  }
  setYamlField(lines, "proxy", "type", yamlString(proxy.type));
  setYamlField(lines, "proxy", "host", yamlString(proxy.host));
  setYamlField(lines, "proxy", "port", String(proxy.port));
}

function removeYamlSection(lines: string[], sectionIndex: number): void {
  let end = sectionIndex + 1;
  while (end < lines.length && !/^\S/.test(lines[end] ?? "")) {
    end++;
  }
  lines.splice(sectionIndex, end - sectionIndex);
}

function renderProxySection(proxy: LocalProxySettings | undefined): string[] {
  if (!isUsableProxy(proxy)) {
    return [];
  }
  return [
    "proxy:",
    `  type: ${yamlString(proxy.type)}`,
    `  host: ${yamlString(proxy.host)}`,
    `  port: ${proxy.port}`,
    ""
  ];
}

function isUsableProxy(
  proxy: LocalProxySettings | undefined
): proxy is LocalProxySettings & { port: number } {
  if (proxy === undefined || proxy.type === "none" || proxy.host.trim().length === 0
    || proxy.port === null) {
    return false;
  }
  const port = proxy.port;
  return Number.isInteger(port) && port >= 1 && port <= 65_535;
}

function setYamlField(lines: string[], section: string, key: string, value: string): void {
  const sectionIndex = lines.findIndex((line) => new RegExp(`^${section}:\\s*$`).test(line));
  if (sectionIndex < 0) {
    if (lines.length > 0 && lines[lines.length - 1] !== "") {
      lines.push("");
    }
    lines.push(`${section}:`, `  ${key}: ${value}`);
    return;
  }
  let end = sectionIndex + 1;
  while (end < lines.length && !/^\S/.test(lines[end] ?? "")) {
    end++;
  }
  const fieldIndex = lines.slice(sectionIndex + 1, end)
    .findIndex((line) => new RegExp(`^\\s+${key}:`).test(line));
  if (fieldIndex >= 0) {
    const actualIndex = sectionIndex + 1 + fieldIndex;
    const indentation = (lines[actualIndex]?.match(/^\s*/) ?? ["  "])[0];
    lines[actualIndex] = `${indentation}${key}: ${value}`;
  } else {
    lines.splice(sectionIndex + 1, 0, `  ${key}: ${value}`);
  }
}

function yamlString(value: string): string {
  return JSON.stringify(value.replace(/\\/g, "/"));
}

async function atomicWrite(filePath: string, content: string): Promise<void> {
  const temporary = `${filePath}.${process.pid}.tmp`;
  await writeFile(temporary, content, "utf8");
  await rename(temporary, filePath);
}
